// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBLwqqEg6Oygt7077phgFbCX9UkVA9gc70',
    appId: '1:1068472238354:android:d65bcf5fa7920d5d53b3cb',
    messagingSenderId: '1068472238354',
    projectId: 'shoppingapp-e19f3',
    storageBucket: 'shoppingapp-e19f3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBcWPdb-lYrEzaAQ4V0wvj9yfGZFvKr8zU',
    appId: '1:1068472238354:ios:bdb32f4224a675f553b3cb',
    messagingSenderId: '1068472238354',
    projectId: 'shoppingapp-e19f3',
    storageBucket: 'shoppingapp-e19f3.firebasestorage.app',
    androidClientId: '1068472238354-86e4lcbov63mev8g50l5bt9hg1739c0r.apps.googleusercontent.com',
    iosClientId: '1068472238354-klvhioom37tg44jfkpm3j8e2bo50t2s9.apps.googleusercontent.com',
    iosBundleId: 'com.example.eCommerce',
  );

}